
@startuml

class Controller
class Database
class Conversation
class Message
class Server
class Connection
class File

Controller "1" *-- "many" Conversation : has many >
Controller "1" *-- "1" Database : has one >
Controller "1" *-- "1" Server : has one >
Conversation "1" *-- "many" Message : contains >
Conversation "1" *-- "many" File : contains >
Server ..> Conversation : create >
Conversation "1" *-* "1" Connection : has one >

class Controller {
manage everything
..
-std::shared_ptr<Conversation>
currentConversation
-QVector<Conversation>
conversations
-std::unique_ptr<Server>
tcpServer
-std::unique_ptr<Database>
db
--
+Controller()
+void onChangeConversation()
+void onNewConnection(QTcpSocket*)
-bool acceptConncetion()
}

class Conversation {
+Conversation(QTcpSocket*)
+void sendMessage()
+void onReceivedMessage()
+void setName(QString name)
+QString getName()
+QVector<Message> getMessages()
+QVector<File> getFiles()
-QVector<Message> messages
-QVector<File> files
-QString name
-std::unique_ptr<Connection>
connection
-bool isConnected
}

class Message {
+QString getText()
+void setText()
-QString text
-bool isSender
}

class Server {
manage incoming connection
..
-QTcpServer tcpServer
--
+void makeNewConnection()
}

class Connection {
+void onReceivedMessage()
+void onSentMessage()
-QTcpSocket socket
}

class File {
+QString getName()
-QFile file
-bool isSender
}

class Database {
-std::unique_ptr<QSqlDatabase>
+void storeConversation(const Conversation&)
+void onNewMessage(const QString&)
+void onNewFile(const File&)
+QVector<Conversation> loadConversations()
-void storeMessage(const Message&)
-void storeFile(const File&)
-QVector<Message> loadMessages()
-QVector<File>  loadFiles()
}

@enduml
